[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
creator_dao = "89tL9Ht9DvKaKjoAovBAaACsD9kL9VCDx9vzFbAuqsjD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./new_keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
